export enum ActionTypes {
    SET_STRING = "SET_STRING",
    GET_STRING = "GET_STRING",
    LIST_PUSH_FRONT = "LIST_PUSH_FRONT",
    LIST_PUSH_BACK = "LIST_PUSH_BACK",
    LIST_POP_FRONT = "LIST_POP_FRONT",
    LIST_POP_BACK = "LIST_POP_BACK",
    SET_ADD = "SET_ADD",
    SET_REMOVE = "SET_REMOVE",
    SET_MEMBERS = "SET_MEMBERS",
    HASH_SET_FIELD = "HASH_SET_FIELD",
    HASH_GET_FIELD = "HASH_GET_FIELD",
    HASH_DELETE_FIELD = "HASH_DELETE_FIELD",
    HASH_GET_ALL = "HASH_GET_ALL"
}
