export enum ActionTypes {
    SET = "SET",
    GET = "GET",
    LPUSH = "LPUSH",
    RPUSH = "RPUSH",
    LPOP = "LPOP",
    RPOP = "RPOP",
    SADD = "SADD",
    SREM = "SREM",
    SMEMBERS = "SMEMBERS",
    HSET = "HSET",
    HGET = "HGET",
    HDEL = "HDEL",
    HGETALL = "HGETALL",
    PING = "PING",
}
